In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("C:/Users/91918/Downloads/Churn_Modelling.csv")

In [3]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age   
0             1    15634602   Hargrave          619    France  Female   42  \
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember   
0          2       0.00              1          1               1  \
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
x = dataset.iloc[:, 3:13].values
y = dataset.iloc[:,13].values

In [5]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [7]:
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
p = LabelEncoder()
x[:,2] = p.fit_transform(x[:,2])

In [12]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [18]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('ohe', OneHotEncoder(),[1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x), dtype = np.str_)

In [21]:
x = x[:,1:]
print(x)

[['1.0' '0.0' '619' ... '1' '1' '101348.88']
 ['0.0' '1.0' '608' ... '0' '1' '112542.58']
 ['1.0' '0.0' '502' ... '1' '0' '113931.57']
 ...
 ['1.0' '0.0' '709' ... '0' '1' '42085.58']
 ['0.0' '0.0' '772' ... '1' '0' '92888.52']
 ['1.0' '0.0' '792' ... '1' '0' '38190.78']]


In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [26]:
import pandas as pd
print(x_train)

[[-1.01460667  1.74309049  0.16958176 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667 -0.57369368 -2.30455945 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.57369368 -1.19119591 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.57369368  0.9015152  ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667  1.74309049 -0.62420521 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667 -0.57369368 -0.28401079 ...  0.64259497 -1.03227043
   0.32472465]]


In [27]:
pd.DataFrame(x_train)

0         1         2         3         4         5         6    
0    -1.014607  1.743090  0.169582 -1.091687 -0.464608  0.006661 -1.215717  \
1    -1.014607 -0.573694 -2.304559  0.916013  0.301026 -1.377440 -0.006312   
2     0.985604 -0.573694 -1.191196 -1.091687 -0.943129 -1.031415  0.579935   
3    -1.014607  1.743090  0.035566  0.916013  0.109617  0.006661  0.473128   
4    -1.014607  1.743090  2.056114 -1.091687  1.736588  1.044737  0.810193   
...        ...       ...       ...       ...       ...       ...       ...   
7995 -1.014607 -0.573694 -0.582970 -1.091687 -0.656016 -0.339364  0.703104   
7996 -1.014607  1.743090  1.478815 -1.091687 -1.613058 -0.339364  0.613060   
7997  0.985604 -0.573694  0.901515  0.916013 -0.368904  0.006661  1.361474   
7998 -1.014607  1.743090 -0.624205 -1.091687 -0.081791  1.390762 -1.215717   
7999 -1.014607 -0.573694 -0.284011 -1.091687  0.875251 -1.377440  0.511364   

            7         8         9         10  
0     0.809503  0.642595 -1.032270  1.106432  
1    -0.921591  0.642595  0.968738 -0.748664  
2    -0.921591  0.642595 -1.032270  1.485335  
3    -0.921591  0.642595 -1.032270  1.276528  
4     0.809503  0.642595  0.968738  0.558378  
...        ...       ...       ...       ...  
7995  0.809503  0.642595  0.968738  1.091330  
7996 -0.921591  0.642595  0.968738  0.131760  
7997  0.809503  0.642595 -1.032270  1.412320  
7998  0.809503  0.642595  0.968738  0.844321  
7999 -0.921591  0.642595 -1.032270  0.324725  

[8000 rows x 11 columns]

In [29]:
!pip install keras

     ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
     - -------------------------------------- 0.1/1.7 MB 1.1 MB/s eta 0:00:02
     -- ------------------------------------- 0.1/1.7 MB 1.3 MB/s eta 0:00:02
     ----- ---------------------------------- 0.2/1.7 MB 1.9 MB/s eta 0:00:01
     --------- ------------------------------ 0.4/1.7 MB 2.3 MB/s eta 0:00:01
     ------------ --------------------------- 0.5/1.7 MB 2.3 MB/s eta 0:00:01
     ---------------- ----------------------- 0.7/1.7 MB 2.6 MB/s eta 0:00:01
     ------------------- -------------------- 0.8/1.7 MB 2.7 MB/s eta 0:00:01
     ---------------------- ----------------- 1.0/1.7 MB 2.7 MB/s eta 0:00:01
     -------------------------- ------------- 1.2/1.7 MB 2.9 MB/s eta 0:00:01
     ----------------------------- ---------- 1.3/1.7 MB 2.8 MB/s eta 0:00:01
     --------------------------------- ------ 1.5/1.7 MB 2.8 MB/s eta 0:00:01
     ------------------------------------ --- 1.6/1.7 MB 2.9 MB/s eta 0


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [34]:
!pip install tensorflow

  Using cached tensorflow-2.12.0-cp310-cp310-win_amd64.whl (1.9 kB)
  Using cached tensorflow_intel-2.12.0-cp310-cp310-win_amd64.whl (272.8 MB)
  Using cached tensorboard-2.12.3-py3-none-any.whl (5.6 MB)
  Using cached jax-0.4.12-py3-none-any.whl
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached grpcio-1.54.2-cp310-cp310-win_amd64.whl (4.1 MB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached h5py-3.9.0-cp310-cp310-win_amd64.whl (2.7 MB)
  Using cached ml_dtypes-0.2.0-cp310-cp310-win_amd64.whl (938 kB)
  Using cached Markdown-3.4.3-py3-none-any.whl (93 kB)
  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
  Using cached google_auth-2.20.0-py2.py3-none-any.whl (181 kB)
  Using cached cachetools-5.3.1-py3-none-any.whl (9.3 kB)
  Using cached rsa-4.9-py3-non


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [36]:
from tensorflow.keras.models import Sequential
from keras.layers import Dense

In [37]:
classifier = Sequential()

In [66]:
classifier.add(Dense(units=6, kernel_initializer="uniform", activation = "relu", input_dim = 11))

In [67]:
classifier.add(Dense(units=6, kernel_initializer="uniform", activation = "relu"))

In [68]:
classifier.add(Dense(units=1, kernel_initializer="uniform", activation = "sigmoid"))

In [69]:
classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

In [70]:
classifier.fit(x_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 4s 3ms/step - loss: 0.5466 - accuracy: 0.7955
Epoch 2/100
800/800 [==============================] - 2s 3ms/step - loss: 0.5014 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4956 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4854 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4683 - accuracy: 0.7960
Epoch 6/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4491 - accuracy: 0.7960
Epoch 7/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4393 - accuracy: 0.7960
Epoch 8/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4362 - accuracy: 0.7960
Epoch 9/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4345 - accuracy: 0.7960
Epoch 10/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4332 - accura

In [71]:
y_pred = classifier.predict(x_test)
y_pred = (y_pred>0.5)

63/63 [==============================] - 0s 2ms/step


In [52]:
print(y_pred)

[[ True  True False  True  True  True]
 [ True False False False False False]
 [ True  True  True  True  True  True]
 ...
 [ True  True False  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True False  True  True  True]]


In [72]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

In [73]:
print(cm)

[[1538   57]
 [ 258  147]]


In [74]:
accuracy_score(y_test, y_pred)

0.8425